### ISSUE TITLE
No need tin the OLD sheet

### ISSUE THREAD

**Issue by Alita2005** [EtoileLion/Roll20-WOIN#3]
Vital Defense is not used in the OLD system

**Comment by EtoileLion** [comment]
The sheet was built off of N.E.W. 1.2, which added Vital Defense and revised the Status Track/Condition system. Uncertain if O.L.D. will receive the same treatment, so I'm going to hold off on generating an entirely different template for it yet.

**Comment by EtoileLion** [comment]
Correction - There IS Vital Defense and the new Status system in O.L.D. - it's covered in the [Errata document](http://www.woinrpg.com/s/old_errata_v11b.pdf).
